wt: sync

diff --git a/bin/sync-windows-terminal b/bin/sync-windows-terminal
--- a/bin/sync-windows-terminal
+++ b/bin/sync-windows-terminal
@@ -2,11 +2,11 @@
 # shellcheck disable=SC2086
 
 winhome="$(wslpath "$(wslvar USERPROFILE)")"
-settings="$winhome/AppData/Local/Packages/Microsoft.WindowsTerminal*/LocalState/settings.json"
+settings="$winhome/AppData/Local/Packages/Microsoft.WindowsTerminal_*/LocalState/settings.json"
 
 if ! [ -r $settings ]; then
-	echo "Couldn't find Windows Terminal settings at $settings"
-	exit 1
+        echo "Couldn't find Windows Terminal settings at $settings"
+        exit 1
 fi
 
 cp $settings "$HOME/.config/windows.terminal/settings.json"
